{
"name": "Odoo AI Bridge",
"version": "19.0.0.4.0",
"summary": "Secure read-only connector for Speak To Your Database.",
"category": "Tools",
"author": "Speak To Your Database",
"website": "https://speaktoyourdatabase.com",
"license": "LGPL-3",
"depends": ["base"],
"data": [
"security/ir.model.access.csv",
"views/res_config_settings_views.xml",
"views/bridge_access_log_views.xml",
"views/bridge_status_views.xml",
"views/bridge_setup_views.xml",
],
"images": [
"static/description/images/bridge-connection-setup.png",
"static/description/images/styd-odoo-bridge-connected.png",
"static/description/images/bridge-total-sales-answer.png",
"static/description/images/bridge-how-calculated.png",
],
"installable": True,
"application": True,
}
